#!/usr/bin/env node
// Turn the locally seeded EmDash SQLite DB into SQL that loads a Cloudflare D1.
//
//   npx emdash seed --on-conflict update        # repo root: writes ./data.db from .emdash/seed.json
//   node scripts/emdash/d1-sql.mjs              # writes scripts/emdash/out/d1-load.sql
//   npx wrangler d1 execute DB --env preview --remote --file scripts/emdash/out/d1-load.sql
//
// Why: the docs collection table (ec_docs), the sidebar menu and the search
// index are created by EmDash at seed time, not by its migrations, and loading
// over REST needs an admin API token, which needs a first sign-in. This path
// needs neither. It is meant for a NEW database (preview, or production before
// cutover). Every statement is idempotent: CREATE ... IF NOT EXISTS and
// INSERT OR REPLACE, then the search index is rebuilt from scratch.
// Do not run it against a database people have edited: it overwrites pages.
//
//   --database <path>   SQLite file (default ./data.db)
//   --out <path>        output (default scripts/emdash/out/d1-load.sql)
import { DatabaseSync } from "node:sqlite";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const arg = (k, d) => {
  const i = process.argv.indexOf(k);
  return i > 0 ? process.argv[i + 1] : d;
};
const dbPath = arg("--database", "./data.db");
const out = arg("--out", join(here, "out", "d1-load.sql"));

const db = new DatabaseSync(dbPath, { readOnly: true });
const FTS = /^_emdash_fts_/; // FTS5 virtual tables and their shadow tables
const NO_ROWS = new Set(["_emdash_migrations_lock", "_emdash_redirect_write_lock"]); // lock rows are runtime state

export const quote = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number" || typeof v === "bigint") return String(v);
  if (v instanceof Uint8Array) return `X'${Buffer.from(v).toString("hex")}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const ident = (s) => `"${s.replace(/"/g, '""')}"`;
const ifNotExists = (sql) => sql.replace(/^CREATE (UNIQUE INDEX|INDEX|TABLE|TRIGGER|VIEW|VIRTUAL TABLE) (?!IF NOT EXISTS)/i, "CREATE $1 IF NOT EXISTS ");

const objects = db.prepare("SELECT type, name, tbl_name, sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY rowid").all();
const tables = objects.filter((o) => o.type === "table" && !FTS.test(o.name));
const ftsTables = objects.filter((o) => o.type === "table" && /^_emdash_fts_[a-z0-9_]+$/i.test(o.name) && /VIRTUAL TABLE/i.test(o.sql));
const ftsNames = new Set(ftsTables.map((t) => t.name));
const indexes = objects.filter((o) => o.type === "index" && !FTS.test(o.tbl_name));
const triggers = objects.filter((o) => o.type === "trigger");

const lines = ["-- Generated by scripts/emdash/d1-sql.mjs from " + dbPath.replace(/\\/g, "/") + ". Idempotent; see the header of that script.", "PRAGMA defer_foreign_keys = true;"];
for (const t of tables) lines.push(ifNotExists(t.sql) + ";");
for (const t of ftsTables) lines.push(ifNotExists(t.sql) + ";");
let rows = 0;
for (const t of tables) {
  if (NO_ROWS.has(t.name)) continue;
  for (const r of db.prepare(`SELECT * FROM ${ident(t.name)}`).all()) {
    const cols = Object.keys(r);
    lines.push(`INSERT OR REPLACE INTO ${ident(t.name)} (${cols.map(ident).join(", ")}) VALUES (${cols.map((c) => quote(r[c])).join(", ")});`);
    rows++;
  }
}
for (const i of indexes) lines.push(ifNotExists(i.sql) + ";");
// Rebuild each search index from the seeded copy (inserting pages above may
// have fired the sync triggers on a database that already had them).
for (const t of ftsTables) {
  lines.push(`DELETE FROM ${ident(t.name)};`);
  const cols = db.prepare(`PRAGMA table_info(${ident(t.name)})`).all().map((c) => c.name);
  for (const r of db.prepare(`SELECT ${cols.map(ident).join(", ")} FROM ${ident(t.name)}`).all())
    lines.push(`INSERT INTO ${ident(t.name)} (${cols.map(ident).join(", ")}) VALUES (${cols.map((c) => quote(r[c])).join(", ")});`);
}
for (const tr of triggers) lines.push(ifNotExists(tr.sql) + ";");

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n") + "\n");
console.log(`wrote ${out}: ${tables.length} tables, ${rows} rows, ${ftsNames.size} search index(es), ${triggers.length} triggers`);
